# Generated by Django 4.2.7 on 2023-11-11 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado em"),
                ),
                (
                    "requester",
                    models.CharField(max_length=100, verbose_name="Solicitantes"),
                ),
                (
                    "department",
                    models.CharField(max_length=100, verbose_name="Departamento"),
                ),
                ("description", models.TextField(verbose_name="Descrição do chamado")),
                (
                    "started_in",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Aberto"),
                            ("IN_SERVICE", "Em atendimento"),
                            ("CLOSED", "Encerrado"),
                            ("CANCELED", "Cancelado"),
                        ],
                        default="OPEN",
                        editable=False,
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "closed_in",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_company",
                        to="companies.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsible_tick",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
